### ISSUE TITLE
마지막 공지

### ISSUE THREAD

**Issue by seongssu** [5-jojojojojo/5team#115]
1. README에 들어갈 MyPage, VideoDetail GIF형식 짧은 영상하나씩 부탁드립니다. 25메가안넘게 부탁드려요
2. README 추가할부분 추가하시고, 수정할부분 수정하시면됩니다.
3. Main에 merge해놨읍니다. 추가할 내용없으면 브랜치 삭제하세요!
4. 검색부분 예외처리 해놨는데 혹시나 마지막으로 점검부탁드려요!
5. 모두들 정말 고생많으셨습니다. 또뵈요!

완료!

**Comment by dklee1619** [comment]
마지막까지 다들 안해봐서 어려워하는 Read.me 작성하시느라 고생많으셨습니다 ㅠㅠ
성수님이랑 현정님이랑 팀이여서 넘넘 행복했어요 최종때도 행복하세요
