### ISSUE TITLE
패키지 경로가 없는 형태 변경 필요해요. / 패키지명 대문자 권장하지 않아요

### ISSUE THREAD

**Issue by khjgggg** [5-jojojojojo/5team#21]
1. 동일 클래스명이 존재하여 한쪽을 패키지 경로를 없애서 디폴트 경로로 만들면 객체 참조 문제가 발생할 수 있습니다.

ChannelData 클래스명을 변경해서 동일한 클래스명 사용하지 않는 것이 좋아요.
![화면 캡처 2023-09-27 035439](https://github.com/5-jojojojojo/5team/assets/139103508/38751f92-a4f4-4215-9213-d3c73400f240)

위와같이 바꾸면  VideoData.kt  파일의 패키지 경로를 다시 지정해주는 것을 권장해요.

2.  패키지는 소문자 권장

**Comment by seongssu** [comment]
확인 했습니다 조심할께요!
